### ISSUE TITLE
Support for Raspberry Pi?

### ISSUE THREAD

**Issue by kelanel** [BenjaminPrice/fvtt-docker#13]
Getting a `tandard_init_linux.go:211: exec user process caused "exec format error"`  when it's launched via an RPi4, Would you be willing to update the dockerhub image builds to also support arm?

**Comment by BenjaminPrice** [comment]
Sorry, I don't have an ARM device to test this with. I'm willing to merge something if someone else wants to put together a Pull Request. Otherwise, this won't be happening until I get a device.
