### ISSUE TITLE
Upgrading Versions fails

### ISSUE THREAD

**Issue by hno2** [BenjaminPrice/fvtt-docker#14]
It is currently impossible to update/upgrade to a newer version.
If you want to update to a newer version (e.g. from 0.6.x to 0.7.x) the container is restarted and will unzip the zip file provided, overwriting the update.

Maybe adding an additional volume for the foundry internal files is an option?

Or an other option would be to follow the structure of this [docker-compose](https://github.com/felddy/foundryvtt-docker) and disable the update dialogue.

**Comment by jero-rodriguez** [comment]
Same problem here, I don´t know why loop on the unzip phase.
