### ISSUE TITLE
Node version needs updating.

### ISSUE THREAD

**Issue by burchbobby** [BenjaminPrice/fvtt-docker#16]
Can't upgrade to beta branch (or stable, soon) 0.8.5 due to Node version dependency.

**Comment by Wiliver** [comment]
Stable is now 0.8.6 so upgrade broke for me

**Comment by joshuacook** [comment]
Did you pull the latest image?

**Comment by OtavioLhamas** [comment]
> > Can't upgrade to beta branch (or stable, soon) 0.8.5 due to Node version dependency.
> 
> Did you pull the latest image?

I just did, tried recreating the Docker container to no success, NODE_VERSION still says 12.18.2.

**Comment by joshuacook** [comment]
You'll have to recreate the provisioning in portainer.

**Comment by BenjaminPrice** [comment]
As you can see in this [commit](https://github.com/BenjaminPrice/fvtt-docker/commit/0b5c6699bf0e642287764db051832508096fd6fa), the node version has been bumped. You'll need to delete your cached docker images or force a rebuild of the image.
