### ISSUE TITLE
Foundry v9 Release

### ISSUE THREAD

**Issue by muckaluck1** [BenjaminPrice/fvtt-docker#24]
Foundry has included upper case letters in their new zip file.  Upgrades won't happen until you've renamed it.

Container logs in portainer for Foundry:

}

cp: can't stat '/host/foundryvtt*.zip': No such file or directory

unzip: can't open foundryvtt*.zip[.zip]

rm: can't remove 'foundryvtt*.zip': No such file or directory

node:internal/modules/cjs/loader:944


  throw err;

  ^

Error: Cannot find module '/opt/foundryvtt/resources/app/main.js'

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)

    at Function.Module._load (node:internal/modules/cjs/loader:774:27)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

    at node:internal/main/run_main_module:17:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

**Comment by maschill92** [comment]
Here's an example of the new file format: `FoundryVTT-9.242.zip`

**Comment by marcwagner** [comment]
I made a pull request that will fix this issue
https://github.com/BenjaminPrice/fvtt-docker/pull/25

in the meanwhile, feel free to use my own merged / tested docker image:
marcwagner/foundry-docker:latest
