### ISSUE TITLE
Incorrect volume instruction for login screen customization

### ISSUE THREAD

**Issue by Vourliotis** [BenjaminPrice/fvtt-docker#27]
PR #26 tried to fix issue #23 by adding a volume instruction to the app's directory.
Unfortunately the volume was incorrect which means the files are still not accessible.

**Comment by marcwagner** [comment]
I made the original pull request and realized my documentation was not good enough. appologies. I have updated the documentation in this PR, which should now work. would you like to review it?

https://github.com/marcwagner/fvtt-docker/

**Comment by Vourliotis** [comment]
Hello @marcwagner!

The updated documentation seems fine! The problem before was the incorrect path that was used which I see you fixed in https://github.com/marcwagner/fvtt-docker/commit/df53795b4e7b5bf1b8d72002bce3fc3d903e92d7. I opened a PR here as well (#27) to fix this issue but whichever gets merged will work just fine!

**Comment by marcwagner** [comment]
excellent. I made one last change and created a pull request. I hope @BenjaminPrice merges it soon.

**Comment by BenjaminPrice** [comment]
Thanks for this. Sorry I didn't see this sooner.
