### ISSUE TITLE
update stuck at Installing update files 0%

### ISSUE THREAD

**Issue by Apollo55** [BenjaminPrice/fvtt-docker#34]
Hi,

I discoverd when try to update foundry using the Update Tab it will get stuck at 0%.
Can you give instuctions how to update?

`fvtt  | FoundryVTT | 2022-12-29 18:23:33 | [info] Core software stable update 10.291 is available!
fvtt  | FoundryVTT | 2022-12-29 18:23:38 | [info] Core software stable update 10.291 is available!
fvtt  | FoundryVTT | 2022-12-29 18:23:42 | [info] Downloading software update - 1%
fvtt  | FoundryVTT | 2022-12-29 18:23:42 | [info] Downloading software update - 2%
fvtt  | FoundryVTT | 2022-12-29 18:23:42 | [info] Downloading software update - 3%
fvtt  | FoundryVTT | 2022-12-29 18:23:43 | [info] Downloading software update - 4%
fvtt  | FoundryVTT | 2022-12-29 18:23:43 | [info] Downloading software update - 5%
fvtt  | FoundryVTT | 2022-12-29 18:23:43 | [info] Downloading software update - 6%
fvtt  | FoundryVTT | 2022-12-29 18:23:43 | [info] Downloading software update - 7%
fvtt  | FoundryVTT | 2022-12-29 18:23:44 | [info] Downloading software update - 8%
fvtt  | FoundryVTT | 2022-12-29 18:23:44 | [info] Downloading software update - 9%
fvtt  | FoundryVTT | 2022-12-29 18:23:44 | [info] Downloading software update - 10%
fvtt  | FoundryVTT | 2022-12-29 18:23:44 | [info] Downloading software update - 11%
fvtt  | FoundryVTT | 2022-12-29 18:23:45 | [info] Downloading software update - 12%
fvtt  | FoundryVTT | 2022-12-29 18:23:45 | [info] Downloading software update - 13%
fvtt  | FoundryVTT | 2022-12-29 18:23:45 | [info] Downloading software update - 14%
fvtt  | FoundryVTT | 2022-12-29 18:23:45 | [info] Downloading software update - 15%
fvtt  | FoundryVTT | 2022-12-29 18:23:45 | [info] Downloading software update - 16%
fvtt  | FoundryVTT | 2022-12-29 18:23:46 | [info] Downloading software update - 17%
fvtt  | FoundryVTT | 2022-12-29 18:23:46 | [info] Downloading software update - 18%
fvtt  | FoundryVTT | 2022-12-29 18:23:46 | [info] Downloading software update - 19%
fvtt  | FoundryVTT | 2022-12-29 18:23:46 | [info] Downloading software update - 20%
fvtt  | FoundryVTT | 2022-12-29 18:23:46 | [info] Downloading software update - 21%
fvtt  | FoundryVTT | 2022-12-29 18:23:47 | [info] Downloading software update - 22%
fvtt  | FoundryVTT | 2022-12-29 18:23:47 | [info] Downloading software update - 23%
fvtt  | FoundryVTT | 2022-12-29 18:23:47 | [info] Downloading software update - 24%
fvtt  | FoundryVTT | 2022-12-29 18:23:47 | [info] Downloading software update - 25%
fvtt  | FoundryVTT | 2022-12-29 18:23:47 | [info] Downloading software update - 26%
fvtt  | FoundryVTT | 2022-12-29 18:23:48 | [info] Downloading software update - 27%
fvtt  | FoundryVTT | 2022-12-29 18:23:48 | [info] Downloading software update - 28%
fvtt  | FoundryVTT | 2022-12-29 18:23:48 | [info] Downloading software update - 29%
fvtt  | FoundryVTT | 2022-12-29 18:23:48 | [info] Downloading software update - 30%
fvtt  | FoundryVTT | 2022-12-29 18:23:48 | [info] Downloading software update - 31%
fvtt  | FoundryVTT | 2022-12-29 18:23:49 | [info] Downloading software update - 32%
fvtt  | FoundryVTT | 2022-12-29 18:23:49 | [info] Downloading software update - 33%
fvtt  | FoundryVTT | 2022-12-29 18:23:49 | [info] Downloading software update - 34%
fvtt  | FoundryVTT | 2022-12-29 18:23:49 | [info] Downloading software update - 35%
fvtt  | FoundryVTT | 2022-12-29 18:23:49 | [info] Downloading software update - 36%
fvtt  | FoundryVTT | 2022-12-29 18:23:50 | [info] Downloading software update - 37%
fvtt  | FoundryVTT | 2022-12-29 18:23:50 | [info] Downloading software update - 38%
fvtt  | FoundryVTT | 2022-12-29 18:23:50 | [info] Downloading software update - 39%
fvtt  | FoundryVTT | 2022-12-29 18:23:50 | [info] Downloading software update - 40%
fvtt  | FoundryVTT | 2022-12-29 18:23:50 | [info] Downloading software update - 41%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 42%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 43%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 44%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 45%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 46%
fvtt  | FoundryVTT | 2022-12-29 18:23:51 | [info] Downloading software update - 47%
fvtt  | FoundryVTT | 2022-12-29 18:23:52 | [info] Downloading software update - 48%
fvtt  | FoundryVTT | 2022-12-29 18:23:52 | [info] Downloading software update - 49%
fvtt  | FoundryVTT | 2022-12-29 18:23:52 | [info] Downloading software update - 50%
fvtt  | FoundryVTT | 2022-12-29 18:23:52 | [info] Downloading software update - 51%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 52%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 53%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 54%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 55%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 56%
fvtt  | FoundryVTT | 2022-12-29 18:23:53 | [info] Downloading software update - 57%
fvtt  | FoundryVTT | 2022-12-29 18:23:54 | [info] Downloading software update - 58%
fvtt  | FoundryVTT | 2022-12-29 18:23:54 | [info] Downloading software update - 59%
fvtt  | FoundryVTT | 2022-12-29 18:23:54 | [info] Downloading software update - 60%
fvtt  | FoundryVTT | 2022-12-29 18:23:54 | [info] Downloading software update - 61%
fvtt  | FoundryVTT | 2022-12-29 18:23:54 | [info] Downloading software update - 62%
fvtt  | FoundryVTT | 2022-12-29 18:23:55 | [info] Downloading software update - 63%
fvtt  | FoundryVTT | 2022-12-29 18:23:55 | [info] Downloading software update - 64%
fvtt  | FoundryVTT | 2022-12-29 18:23:55 | [info] Downloading software update - 65%
fvtt  | FoundryVTT | 2022-12-29 18:23:55 | [info] Downloading software update - 66%
fvtt  | FoundryVTT | 2022-12-29 18:23:55 | [info] Downloading software update - 67%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 68%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 69%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 70%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 71%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 72%
fvtt  | FoundryVTT | 2022-12-29 18:23:56 | [info] Downloading software update - 73%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 74%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 75%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 76%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 77%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 78%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 79%
fvtt  | FoundryVTT | 2022-12-29 18:23:57 | [info] Downloading software update - 80%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 81%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 82%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 83%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 84%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 85%
fvtt  | FoundryVTT | 2022-12-29 18:23:58 | [info] Downloading software update - 86%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 87%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 88%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 89%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 90%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 91%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 92%
fvtt  | FoundryVTT | 2022-12-29 18:23:59 | [info] Downloading software update - 93%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 94%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 95%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 96%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 97%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 98%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Downloading software update - 99%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Update download complete - 100%
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Extracting downloaded update files
fvtt  | FoundryVTT | 2022-12-29 18:24:00 | [info] Extracting downloaded update files - 1%
fvtt  | FoundryVTT | 2022-12-29 18:24:01 | [info] Extracting downloaded update files - 2%
fvtt  | FoundryVTT | 2022-12-29 18:24:01 | [info] Extracting downloaded update files - 3%
fvtt  | FoundryVTT | 2022-12-29 18:24:01 | [info] Extracting downloaded update files - 4%
fvtt  | FoundryVTT | 2022-12-29 18:24:01 | [info] Extracting downloaded update files - 5%
fvtt  | FoundryVTT | 2022-12-29 18:24:01 | [info] Extracting downloaded update files - 6%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 7%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 8%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 9%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 10%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 11%
fvtt  | FoundryVTT | 2022-12-29 18:24:02 | [info] Extracting downloaded update files - 12%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 13%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 14%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 15%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 16%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 17%
fvtt  | FoundryVTT | 2022-12-29 18:24:03 | [info] Extracting downloaded update files - 18%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 19%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 20%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 21%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 22%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 23%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 24%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 25%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 26%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 27%
fvtt  | FoundryVTT | 2022-12-29 18:24:04 | [info] Extracting downloaded update files - 28%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 29%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 30%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 31%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 32%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 33%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 34%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 35%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 36%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 37%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 38%
fvtt  | FoundryVTT | 2022-12-29 18:24:05 | [info] Extracting downloaded update files - 39%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 40%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 41%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 42%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 43%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 44%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 45%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 46%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 47%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 48%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 49%
fvtt  | FoundryVTT | 2022-12-29 18:24:06 | [info] Extracting downloaded update files - 50%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 51%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 52%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 53%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 54%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 55%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 56%
fvtt  | FoundryVTT | 2022-12-29 18:24:07 | [info] Extracting downloaded update files - 57%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 58%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 59%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 60%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 61%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 62%
fvtt  | FoundryVTT | 2022-12-29 18:24:08 | [info] Extracting downloaded update files - 63%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 64%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 65%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 66%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 67%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 68%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 69%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 70%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 71%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 72%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 73%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 74%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 75%
fvtt  | FoundryVTT | 2022-12-29 18:24:09 | [info] Extracting downloaded update files - 76%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 77%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 78%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 79%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 80%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 81%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 82%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 83%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 84%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 85%
fvtt  | FoundryVTT | 2022-12-29 18:24:10 | [info] Extracting downloaded update files - 86%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 87%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 88%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 89%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 90%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 91%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 92%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 93%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 94%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 95%
fvtt  | FoundryVTT | 2022-12-29 18:24:11 | [info] Extracting downloaded update files - 96%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Extracting downloaded update files - 97%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Extracting downloaded update files - 98%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Extracting downloaded update files - 99%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Update extraction complete - 100%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Cleaning existing folder content - 25%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Cleaning existing folder content - 2%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Cleaning existing folder content - 3%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Folder cleaning complete - 100%
fvtt  | FoundryVTT | 2022-12-29 18:24:12 | [info] Installing update files
`
<img width="784" alt="update" src="https://user-images.githubusercontent.com/17300232/209994624-552d41ba-19ca-4fb4-b638-9c21f57ef743.png">

**Comment by Trashloot** [comment]
Im not sure how you are using the image. Im not an expert on this topic. But in the tutorial i followed it said that you can't use the update button. I use portainer and i just replace the installation file of foundry with a newer file and recreate the container.
